# Generated by Django 5.2.4 on 2025-08-02 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('name', models.CharField(default='Guest', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('base_branch', models.CharField(default='Main Branch', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
