# Generated by Django 5.2.4 on 2025-08-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
    ]
